runtime: python39
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  FLASK_ENV: production
  MAX_CONTENT_LENGTH: "16777216"
  APP_NAME: "IntelliDeck"